import { Op } from 'sequelize'
import Activity from '../models/Activity.js'
import ActivityMember from '../models/ActivityMember.js'
import TripAttendance from '../models/TripAttendance.js'
import { deductReliability } from '../modules/trust/reliability.service.js'
import * as notificationService from '../modules/notifications/notification.service.js'
import logger from '../config/logger.js'

/**
 * Job to scan completed activities for travelers who did not show up.
 * Runs every 15 minutes.
 */
export const runDetectNoShows = async () => {
  const timestamp = new Date().toISOString()
  logger.info(`[JOB START] detectNoShows at ${timestamp}`)

  try {
    // Find completed activities
    const activities = await Activity.findAll({
      where: {
        status: 'completed'
      }
    })

    if (activities.length === 0) {
      logger.info('[JOB END] detectNoShows: 0 activities scanned.')
      return
    }

    let penaltyCount = 0
    let checkedCount = 0

    for (const activity of activities) {
      // Find confirmed members who have not been checked for no-shows yet
      const members = await ActivityMember.findAll({
        where: {
          activity_id: activity.id,
          status: 'confirmed',
          no_show_checked: false
        }
      })

      for (const member of members) {
        // Query host-marked attendance
        const attendance = await TripAttendance.findOne({
          where: {
            activity_id: activity.id,
            user_id: member.user_id
          }
        })

        // No-show if they did not show up (attended is false or no record was generated by host)
        const isNoShow = !attendance || !attendance.attended

        if (isNoShow) {
          // Deduct -20 reliability score
          await deductReliability(member.user_id, 20, 'no_show', activity.id)

          // Send FCM warning notice
          await notificationService.createNotificationRecord(
            member.user_id,
            'score_changed',
            '⚠️ No-Show Penalty Applied',
            `You received a -20 Reliability score penalty for failing to show up at "${activity.title}".`,
            'activity',
            activity.id
          )

          await notificationService.sendFCM(
            member.user_id,
            '⚠️ No-Show Penalty Applied',
            `Your Reliability score was penalized by -20 for no-show at "${activity.title}".`,
            {
              type: 'score_changed',
              referenceType: 'activity',
              referenceId: activity.id
            }
          )

          penaltyCount++
        }

        // Mark this traveler checked for this activity
        member.no_show_checked = true
        await member.save()
        checkedCount++
      }
    }

    logger.info(`[JOB END] detectNoShows: Checked ${checkedCount} travelers, penalized ${penaltyCount} no-shows.`)
  } catch (error) {
    logger.error('[JOB ERROR] detectNoShows failed:', error)
  }
}
